### ISSUE TITLE
Problems getting extension installed

### ISSUE THREAD

**Issue by Andrew120219** [IowaComputerGurus/DnnTelerikIdentifier#3]
I downloaded the zip file from GitHub.  I unblocked the file. I tried to upload the file and get the error that it cannot be uploaded. 

I went to /Portals/default/Logs 
I found this error:

```
021-01-13 09:55:45,682 [CLSRSDEV01][Thread:241][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - SchwabenCode.QuickIO.PathNotFoundException: The system cannot find the path specified.
   at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
   at SchwabenCode.QuickIO.QuickIOFile.OpenFileStream(QuickIOPathInfo pathInfo, FileAccess fileAccess, FileMode fileOption, FileShare shareMode, Int32 buffer)
   at SchwabenCode.QuickIO.QuickIOFile.OpenText(QuickIOPathInfo pathInfo)
   at DotNetNuke.Common.Utilities.FileSystemUtils.ReadFile(String filePath)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadTextFromFile(String source)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadManifest(XPathNavigator manifestNav)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller..ctor(String packageManifest, InstallerInfo info)
   at DotNetNuke.Services.Installer.Installer.ProcessPackages(XPathNavigator rootNav)
   at DotNetNuke.Services.Installer.Installer.ReadManifest(Boolean deleteTemp)
   at Dnn.PersonaBar.Extensions.Components.InstallController.GetInstaller(Stream stream, String fileName, Int32 portalId, String legacySkin, Boolean isPortalPackage)
   at Dnn.PersonaBar.Extensions.Components.InstallController.ParsePackage(PortalSettings portalSettings, UserInfo user, String filePath, Stream stream)
   at Dnn.PersonaBar.Extensions.Services.ExtensionsController.<>c__DisplayClass42_1.<UploadFileAction>b__1(Object <p0>)
   at System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)
```

**Comment by mitchelsellers** [comment]
Are you sure that you downloaded the installer, and not the source

**Comment by Andrew120219** [comment]
Thank you for your reply, Mitch.  After troubleshooting it further it appears that it had something to do with the zip file being in the downloads folder and trying to drag and drop from there.  I moved the zip file from the downloads folder and it worked.  Quirky Windows issue it appears.
